let queryList = [{
        name: "Default",
        source: "none",
        query: "def",
        displayText: "How did we get here?",
        extLink: "https://augystudios.com/",
        descHover: "It looks like you got this link without scanning a QR code or being redirected! What kind of sorcery is that?",
    },
    {
        name: "Legacy Linktree",
        source: "legacy",
        query: "linktree",
        displayText: "You got here from the Legacy Linktree site!",
        extLink: "https://links.augystudios.com/",
        descHover: "Wow, you're a legacy! Click to get back there.",
    },
    {
        name: "GFTV Team ID",
        source: "gftv-team-id",
        query: "tid",
        displayText: "You scanned the QR code on Augy's Global Furry Television (GFTV) Team ID!",
        extLink: "https://globalfurry.tv/",
        descHover: "The GFTV Team ID is a unique identifier of every GFTV Team Member.",
    },
    {
        name: "Name Card 4",
        source: "namecard-4",
        query: "nc-4",
        displayText: "You scanned the QR code on Augy's 4th iteration of his Name Card!",
        extLink: "https://augystudios.com/",
        descHover: "A furry name card is a personal creation that displays everything you need to know about the person you met. Augy's 4th name card features his new Telegram sticker pack's sticker.",
    },
    {
        name: "LIFC 2024",
        source: "lifc24-conbadge",
        query: "lifc24",
        displayText: "You scanned the NFC Tag on Augy's Little Island Furcon (LIFC) 2024 Conbadge!",
        extLink: "https://augystudios.com/",
        descHover: "LIFC is a furry convention held annually in Singapore.",
    },
    {
        name: "FurUM 2024",
        source: "furum24-conbadge",
        query: "furum24",
        displayText: "You scanned the NFC Tag on Augy's Furs Upon Malaysia (FurUM) 2024 Conbadge!",
        extLink: "https://augystudios.com/",
        descHover: "FurUM is a furry convention held annually in Petaling Jaya Malaysia.",
    },
]