let queryList = {
    def: {
        name: "Default",
        source: "none",
        displayText: "How did we get here?",
        extLink: "https://augystudios.com/",
        descHover: "It looks like you got this link without scanning a QR code or being redirected! What kind of sorcery is that?",
        status: "active",
    },
    linktree: {
        name: "Legacy Linktree",
        source: "legacy",
        displayText: "You got here from the Legacy Linktree site!",
        extLink: "https://links.augystudios.com/",
        descHover: "Wow, you're a legacy! Click to get back there.",
        status: "active",
    },
    linkedin: {
        name: "LinkedIn",
        source: "linkedin",
        displayText: "How's the LinkedIn?",
        extLink: "https://www.linkedin.com/in/augyteo/",
        descHover: "Can you believe it? Augy Studios was created in Feb 2013! There's just no LinkedIn page back then. Click to get back there.",
        status: "active",
    },
    social: {
        name: "Social Media",
        source: "socials",
        displayText: "Did you come from Twitter, Telegram, or Instagram?",
        extLink: "https://discord.augystudios.com/",
        descHover: "Share it with us in our Discord server!",
        status: "active",
    },
    bio: {
        name: "Bio from 2021",
        source: "bio-2021",
        displayText: "Are you expecting to see Augy's bio (from 2021)?",
        extLink: "https://paste.hep.gg/raw/etuwi",
        descHover: "You're in luck! Click to get back there.",
        status: "active",
    },
    tid: {
        name: "GFTV Team ID",
        source: "gftv-team-id",
        displayText: "You scanned the QR code on Augy's Global Furry Television (GFTV) Team ID!",
        extLink: "https://globalfurrytv.news.blog/about-us/#jp-carousel-8925",
        descHover: "The GFTV Team ID is a unique identifier of every GFTV Team Member. Augy is an Events Director & Content Editor at GFTV.",
        status: "active",
    },
    "biz-1": {
        name: "Augy Studios Business Card 1",
        source: "bizcard-1",
        displayText: "You scanned the QR code on the first ever Augy Studios business card!",
        extLink: "https://augystudios.com/",
        descHover: "This card is also Augy's first time creating a translucent name card! Click to go to the Augy Studios website.",
        status: "active",
    },
    "nc-1": {
        name: "Augy's Name Card 1",
        source: "namecard-1",
        displayText: "You scanned the QR code on Augy's 1st ever Name Card!",
        extLink: "https://links.augystudios.com/augywolfy",
        descHover: "A furry name card is a personal creation that displays everything you need to know about the person you met. Augy's 1st name card features his old fursona name and species, being a wolf.",
        status: "active",
    },
    "nc-3": {
        name: "Augy's Name Card 3",
        source: "namecard-3",
        displayText: "You scanned the QR code on Augy's 3rd iteration of his Name Card!",
        extLink: "https://augystudios.com/",
        descHover: "A furry name card is a personal creation that displays everything you need to know about the person you met. Augy's 3rd name card features his new Telegram sticker pack's sticker.",
        status: "active",
    },
    lifc24: {
        name: "LIFC 2024",
        source: "lifc24-conbadge",
        displayText: "You scanned the NFC Tag on Augy's Little Island Furcon (LIFC) 2024 Conbadge!",
        extLink: "https://furcon.augystudios.com/sg/lifc-2024",
        descHover: "LIFC is a furry convention held annually in Singapore. This year, Augy is both volunteering and is a Super Sponsor!",
        status: "active",
    },
    furum24: {
        name: "FurUM 2024",
        source: "furum24-conbadge",
        displayText: "You scanned the NFC Tag on Augy's Furs Upon Malaysia (FurUM) 2024 Conbadge!",
        extLink: "https://augystudios.com/",
        descHover: "FurUM is a furry convention held annually in Petaling Jaya Malaysia.",
        status: "inactive",
    }
}